# Generated by Django 5.2.4 on 2026-07-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='city',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='record',
            name='buying_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='record',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='record',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
