# Generated by Django 5.2.4 on 2026-08-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_address_record_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='record',
            old_name='buying_Price',
            new_name='buying_price',
        ),
    ]
