# Generated by Django 5.2.4 on 2026-08-03 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_client_rename_buying_price_record_buying_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='client', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_deposit',
            field=models.CharField(max_length=50),
        ),
    ]
